# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b41dfc0870db258487379524848714099a80dc5ff2334729ca995070202b41225c99d696830eedd33e19b3eac552d36d728ce42110fc8d79ce7a86ba3ba704d4

test:
  secret_key_base: acadffd69913aa17b0a72288c671ec810c5201fc5920f0137bd8cbe12b6b3af0d1ac9245aa6372f9b54ba937e8a42e81351e6283753603842fe2d8f56a84b841

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
